# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-ingress
  namespace: argo-dev-app1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    argo: app1
spec:
  ingressClassName: nginx
  rules:
  - host: cluster
    http:
      paths:
      - path: /argo/app1
        pathType: Prefix
        backend:
          service:
            name: hello-world-service
            port:
              number: 8000
