apiVersion: v1
kind: Service
metadata:
  name: agents-app-service
  namespace: agents-dev
  labels:
    app: agents-app
spec:
  selector:
    app: agents-app
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
